SECRET_KEY = 'you-will-never-guess'
DEBUG = True
#MONGODB_HOST = 'mongodb' # use 'mongodb' if using Docker
MONGODB_HOST ="localhost"
MONGODB_PORT = 27017
MONGODB_DB = 'financial_test'
# MONGODB_DB = 'financial'
#PROTECTED_FOLDER = "/home/lamduyuit/apps/home/data/download_financial/"
PROTECTED_FOLDER = "C:\\Users\\USER\\OneDrive\\whatever.vn\\apps\\home\\data\\download_financial"
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 465
MAIL_USERNAME = "lamduyuit@gmail.com"
MAIL_PASSWORD = "fyqhcygeoyehwquk"
MAIL_USE_TLS = False
MAIL_USE_SSL = True
HOSTNAME = "http://whatever.vn"
RECAPTCHA_PUBLIC_KEY = "6LebHooUAAAAAERifryoMtMVumSTQH8LcxuOMIuH"
RECAPTCHA_PRIVATE_KEY = "6LebHooUAAAAAPErPDlSEodJeOY7j5M6E4fU5dGm"
